import { mkdtemp, mkdir, cp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
const root=await mkdtemp(join(tmpdir(),'aos-codex-native-'));
const vault=join(root,'Codex Addon Isolated QA');
const plugin=join(vault,'.obsidian/plugins/agentic-os-codex');
await mkdir(plugin,{recursive:true});
await cp('build',plugin,{recursive:true});
await mkdir(join(root,'user-data'));
await mkdir(join(root,'codex-home'));
await writeFile(join(vault,'.obsidian/community-plugins.json'),JSON.stringify(['agentic-os-codex']));
await writeFile(join(vault,'.obsidian/app.json'),JSON.stringify({safeMode:false}));
await writeFile(join(vault,'.obsidian/core-plugins.json'),'[]');
await writeFile(join(vault,'.obsidian/workspace.json'),JSON.stringify({main:{id:'test-root',type:'split',children:[{id:'test-pane',type:'leaf',state:{type:'agentic-os-codex-terminal',state:{id:'fixture'}}}],direction:'vertical'},left:{id:'left',type:'split',children:[],direction:'horizontal',width:280,collapsed:true},right:{id:'right',type:'split',children:[],direction:'horizontal',width:280,collapsed:true},active:'test-pane'}));
await writeFile(join(vault,'README.md'),'# Isolated Codex Addon QA\nNo private data, no model calls.\n');
const id=createHash('sha256').update(vault).digest('hex').slice(0,16);
await writeFile(join(root,'user-data/obsidian.json'),JSON.stringify({vaults:{[id]:{path:vault,ts:Date.now(),open:true}}}));
await writeFile('test/native-fixture.json',JSON.stringify({root,vault,plugin},null,2));
console.log(root);
